apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: busybox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command: ["/bin/sh", "-c", "while true; do echo 'Hello from BusyBox'; sleep 5; done"]
